Repository SSoelvsten/adiar, pull requests merged in 2021-12, with the labels that each got.

#178 chore: add `.editorconfig`
  .editorconfig
Labels: chore

#179 chore: add `.gitattributes`
  .gitattributes
Labels: chore

#201 Fix TPIE license notice is based on GPL rather than LGPL
  README.md
  docs/index.md
Labels: documentation

#214 Make priority queues totally ordered in debug mode
  src/adiar/bdd/if_then_else.cpp
  src/adiar/data.h
  src/adiar/internal/intercut.h
  src/adiar/internal/product_construction.h
  src/adiar/internal/quantify.h
  test/adiar/bdd/test_quantify.cpp
  test/adiar/zdd/test_expand.cpp
  test/adiar/zdd/test_subset.cpp
Labels: build system, chore

#215 Improve legibility of unit test output
  test/adiar/bdd/test_apply.cpp
  test/adiar/bdd/test_assignment.cpp
  test/adiar/bdd/test_bdd.cpp
  test/adiar/bdd/test_build.cpp
  test/adiar/bdd/test_count.cpp
  test/adiar/bdd/test_evaluate.cpp
  test/adiar/bdd/test_if_then_else.cpp
  test/adiar/bdd/test_negate.cpp
  test/adiar/bdd/test_quantify.cpp
  test/adiar/bdd/test_restrict.cpp
  test/adiar/internal/test_isomorphism.cpp
  test/adiar/internal/test_levelized_priority_queue.cpp
  test/adiar/internal/test_reduce.cpp
  test/adiar/test_data.cpp
  test/adiar/test_dot.cpp
  test/adiar/test_file.cpp
  test/adiar/zdd/test_binop.cpp
  test/adiar/zdd/test_build.cpp
  test/adiar/zdd/test_change.cpp
  test/adiar/zdd/test_contains.cpp
  test/adiar/zdd/test_count.cpp
  test/adiar/zdd/test_elem.cpp
  test/adiar/zdd/test_expand.cpp
  test/adiar/zdd/test_pred.cpp
  test/adiar/zdd/test_project.cpp
  test/adiar/zdd/test_subset.cpp
  test/adiar/zdd/test_zdd.cpp
Labels: clean up, chore

#223 Use policy pattern in Product Construction helper functions
  src/adiar/internal/product_construction.h
Labels: clean up
