Repository SSoelvsten/adiar, pull requests merged in 2022-02, with the labels that each got.

#253 Add varprofile functions and unit tests
  docs/bdd.md
  docs/zdd.md
  src/adiar/bdd.h
  src/adiar/bdd/bdd.cpp
  src/adiar/bdd/bdd.h
  src/adiar/internal/util.h
  src/adiar/zdd.h
  src/adiar/zdd/zdd.cpp
  test/adiar/internal/test_util.cpp
  test/test.cpp
Labels: enhancement

#261 Add a unit test for two Reduction 1 rule applications on the same level
  test/adiar/internal/test_reduce.cpp
Labels: documentation

#264 Change settings for make test to those for make main and add printing statistics after tests
  makefile
  test/test.cpp
Labels: build system

#274 Decrease memory in phase 1 to circumvent wasteful allocations
  src/adiar/internal/sorter.h
Labels: optimisation

#277 Inline data h
  src/adiar/CMakeLists.txt
  src/adiar/data.cpp
  src/adiar/data.h
  src/adiar/internal/assert.h
Labels: optimisation
