Repository SSoelvsten/adiar, pull requests merged in 2022-07, with the labels that each got.

#367 Change output_dot to use Ø and {Ø} for sinks in ZDDs
  src/adiar/bdd/bdd.cpp
  src/adiar/bdd/bdd.h
  src/adiar/file.h
  src/adiar/internal/dot.h
  src/adiar/zdd/zdd.h
Labels: zdd

#366 Add ability to set a domain for all of adiar
  src/adiar/CMakeLists.txt
  src/adiar/adiar.h
  src/adiar/bdd.h
  src/adiar/bdd/bdd.cpp
  src/adiar/domain.cpp
  src/adiar/domain.h
  src/adiar/zdd.h
  src/adiar/zdd/complement.cpp
  src/adiar/zdd/zdd.cpp
  test/adiar/internal/test_convert.cpp
  test/adiar/test_domain.cpp
  test/adiar/zdd/test_complement.cpp
  test/test.cpp
Labels: enhancement

#375 Fix memory mode persists after deinitialisation
  src/adiar/adiar.cpp
Labels: bug
