Repository SSoelvsten/adiar, pull requests merged in 2022-01, with the labels that each got.

#249 Fix Knight's Tour cannot be made required on Pull Requests
  .github/workflows/examples.yml
Labels: bug, build system, zdd

#251 Add statsreset in adiar_init (closes #234)
  src/adiar/adiar.cpp
  src/adiar/statistics.cpp
  src/adiar/statistics.h
Labels: enhancement

#254 Add benchmarking of smaller instances (closes #246)
  .github/workflows/benchmark.py
  .github/workflows/benchmark.yml
  .github/workflows/system_test.yml
Labels: build system
