Repository SSoelvsten/adiar, pull requests merged in 2022-03, with the labels that each got.

#282 Allow internal_sorter to reuse an allocation
  src/adiar/internal/sorter.h
Labels: optimisation

#290 Use internal memory in if_then_else when possible
  src/adiar/bdd/if_then_else.cpp
  src/adiar/internal/decision_diagram.h
Labels: optimisation

#289 Use internal memory when possible in quantify
  src/adiar/internal/decision_diagram.h
  src/adiar/internal/product_construction.h
  src/adiar/internal/quantify.h
Labels: optimisation

#292 Use internal memory in intercut when possible
  src/adiar/internal/decision_diagram.h
  src/adiar/internal/intercut.h
  src/adiar/internal/levelized_priority_queue.h
Labels: optimisation

#294 Improve performance by reusing allocations of prior sorters
  src/adiar/internal/levelized_priority_queue.h
  src/adiar/internal/sorter.h
Labels: optimisation

#293 Use internal memory in comparison check when possible
  src/adiar/bdd/pred.cpp
  src/adiar/internal/pred.cpp
  src/adiar/internal/pred.h
  src/adiar/zdd/pred.cpp
Labels: optimisation

#300 Add statistics for type of auxilliary data structures
  src/adiar/CMakeLists.txt
  src/adiar/bdd/if_then_else.cpp
  src/adiar/bdd/if_then_else.h
  src/adiar/internal/count.cpp
  src/adiar/internal/count.h
  src/adiar/internal/intercut.cpp
  src/adiar/internal/intercut.h
  src/adiar/internal/pred.h
  src/adiar/internal/product_construction.cpp
  src/adiar/internal/product_construction.h
  src/adiar/internal/quantify.cpp
  src/adiar/internal/quantify.h
  src/adiar/internal/reduce.h
  src/adiar/internal/substitution.cpp
  src/adiar/internal/substitution.h
  src/adiar/statistics.cpp
  src/adiar/statistics.h
Labels: enhancement

#303 Make sure size_bound computations do not overflow and cause wrong choice of auxilliary data structures
  src/adiar/bdd/if_then_else.cpp
  src/adiar/internal/intercut.h
  src/adiar/internal/product_construction.h
  src/adiar/internal/quantify.h
  src/adiar/internal/substitution.h
  src/adiar/internal/util.h
  src/adiar/zdd/pred.cpp
Labels: optimisation

#308 Fix: size_based bounds are off-by-one
  src/adiar/bdd/if_then_else.cpp
  src/adiar/internal/count.h
  src/adiar/internal/intercut.h
  src/adiar/internal/pred.cpp
  src/adiar/internal/pred.h
  src/adiar/internal/product_construction.h
  src/adiar/internal/quantify.h
  src/adiar/internal/substitution.h
  src/adiar/zdd/pred.cpp
Labels: bug
